# Generated by Django 4.2 on 2023-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(default='fio', help_text='ФИО', max_length=128, verbose_name='ФИО студента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(help_text='Выберете курс', through='users.Enrollment', to='posts.course', verbose_name='Курсы пользователя'),
        ),
    ]
