# Generated by Django 4.2 on 2023-04-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='phone_user_constraint',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone', 'fio'), name='phone_fio of constraint'),
        ),
    ]
