# Generated by Django 4.2 on 2023-04-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fio_alter_user_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fio',
        ),
    ]
