version: '3.8'

services:
  db:
    container_name: "db"
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - cts/.env
    ports:
      - "5432:5432"

#  web:
#    build: .
#    restart: always
#    volumes:
#      - static_value:/app/static/
#      - media_value:/app/media/
#    ports:
#     - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - cts/.env
#
#volumes:
#  db_data:
#  static_value:
#  media_value: