version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - cts/.env
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - cts/.env

volumes:
  db_data:
  static_value:
  media_value: