# Generated by Django 4.2 on 2023-04-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.course', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='post',
            name='submit_users',
            field=models.ManyToManyField(help_text='пользователь прошел урок', through='posts.LessonSubmitUser', to=settings.AUTH_USER_MODEL, verbose_name='урок пройден'),
        ),
        migrations.AddField(
            model_name='lessonsubmituser',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submit', to='posts.post'),
        ),
        migrations.AddField(
            model_name='lessonsubmituser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Пост к которому относится коментарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Пост'),
        ),
    ]
