# Generated by Django 4.2 on 2023-04-25 12:21

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата', verbose_name='Дата создания')),
                ('text', models.TextField(help_text='Текст комментария', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок сообщест', max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Адрес сообщест', unique=True, verbose_name='Адрес для страницы с постами')),
                ('description', models.TextField(help_text='Описание сообщест', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='LessonSubmitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата', verbose_name='Дата создания')),
                ('text', ckeditor.fields.RichTextField(blank=True, help_text='Редактируйте статью как вам хочеться', null=True, verbose_name='Статья с редактором')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='вставте ссылку на видео', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
    ]
