# Generated by Django 4.2 on 2023-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, help_text='Введите название статьи', max_length=64, verbose_name='Название статьи'),
            preserve_default=False,
        ),
    ]
